[[session]]
name = "downloads ğŸ“¥"
path = "~/Downloads"
preview_command = "la"

[[session]]
name = "nixfiles âš™ï¸"
path = "~/nixfiles-v2"
startup_command = "lv ."
preview_command = "bat --color=always ~/nixfiles-v2/flake.md"

[[session]]
name = "scratchpad ğŸ—’ï¸"
path = "~/git/github.com/kirksw/scratchpad"
startup_command = "lv ."
preview_command = "bat --color=always ~/git/github.com/kirksw/scratchpad/README.md"

[github]
organization = "lunarway"
cache_timeout = 600
clone_dir = "~/lunarway"
use_ssh = true

sort_order = [
  "tmux",       # show first
  "config",
  "github",     # show GitHub repos after configs
  "tmuxinator",
  "zoxide",     # show last
]
